[package]
name = "mm-plugin-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
wasmtime.workspace = true

[dev-dependencies]
tempfile.workspace = true
wat.workspace = true
