[package]
name = "mm-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "mm"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
flate2.workspace = true
mm-core = { path = "../mm-core" }
mm-plugin-runtime = { path = "../mm-plugin-runtime" }
mm-render = { path = "../mm-render" }
tar.workspace = true

[dev-dependencies]
assert_cmd = "2"
tempfile.workspace = true
