[package]
name = "mm-gui"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
name = "mm_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
fontdb = "0.23"
mm-core = { path = "../../../crates/mm-core" }
mm-plugin-runtime = { path = "../../../crates/mm-plugin-runtime" }
mm-render = { path = "../../../crates/mm-render" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-playwright = "0.2.2"
toml = "0.8"

[dev-dependencies]
tempfile = "3.27.0"

[features]
e2e-testing = []
